# Generated by Django 5.1.5 on 2025-03-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
