# Generated by Django 5.1.5 on 2025-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='device_type',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic Device'), ('therapeutic', 'Therapeutic Device'), ('life_support', 'Life-Support Device'), ('monitoring', 'Monitoring Device'), ('surgical', 'Surgical Device'), ('radiology', 'Radiology Device'), ('lab', 'Laboratory Device'), ('other', 'Other Devices')], db_index=True, default='other', max_length=255),
        ),
    ]
