# Generated by Django 5.0.5 on 2024-10-15 23:02

import cloudinary.models
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('embossment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('repair', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('embossment_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('decommission_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='The type of action performed.', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time the action was logged.')),
                ('changes', models.TextField(help_text='A detailed description of what was changed.')),
                ('reason', models.TextField(blank=True, help_text='The reason for the change.')),
                ('performed_by', models.ForeignKey(help_text='The user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(help_text='The asset that the action was performed on.', on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_draft', models.BooleanField(default=False)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.department'),
        ),
    ]
