# Generated by Django 5.0.5 on 2024-09-26 12:37

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.upload_asset_image),
        ),
    ]
