# Generated by Django 5.0.5 on 2024-09-26 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
