# Generated by Django 5.0.5 on 2024-11-07 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_actionlog_asset_remove_actionlog_performed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_serial_number_when_published',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('serial_number',), name='unique_assets_serial_number_when_published'),
        ),
    ]
