# Generated by Django 5.0.5 on 2024-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_device_type_asset_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
