# Generated by Django 5.0.5 on 2024-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('repair', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20),
        ),
    ]
