# Generated by Django 5.0.5 on 2024-11-15 00:36

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_unique_serial_number_when_published_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
