# Generated by Django 5.0.5 on 2024-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='The type of action performed.', max_length=10),
        ),
    ]
