# Generated by Django 5.0.5 on 2025-01-14 14:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique_with=['name']),
        ),
    ]
