# Generated by Django 5.0.5 on 2025-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_department_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
