# Generated by Django 5.0.5 on 2025-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_asset_device_type_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=10),
        ),
    ]
