# Generated by Django 5.0.5 on 2025-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_maintenanceschedule_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
