# Generated by Django 5.1.5 on 2025-03-12 06:05

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('replacement', 'Replacement Part'), ('maintenance', 'Maintenance Tool'), ('critical', 'Critical Component'), ('consumable', 'Consumables & Accessories'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
