# Generated by Django 5.1.5 on 2025-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('replacement', 'Replacement Part'), ('maintenance', 'Maintenance Tool'), ('critical', 'Critical Component'), ('consumable', 'Consumables & Accessories')], max_length=50),
        ),
    ]
