# Generated by Django 5.0.5 on 2024-11-07 19:32

import autoslug.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalsupplier',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reorder_threshold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='category',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='item',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('name',), name='unique_category_name_when_published'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('serial_number',), name='unique_serial_number_when_published'),
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalItem',
        ),
        migrations.DeleteModel(
            name='HistoricalSupplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
