# Generated by Django 5.0.5 on 2024-09-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
