# Generated by Django 5.0.5 on 2024-11-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_historicalcategory_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_serial_number_when_published',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('serial_number',), name='unique_item_serial_number_when_published'),
        ),
    ]
