# Generated by Django 5.0.5 on 2024-12-01 21:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_unique_serial_number_when_published_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
